TOPICS: list[dict] = [
    # ── Root categories ────────────────────────────────────────────────────────
    {
        "slug": "exposure",
        "title": "Exposure",
        "description": "How light quantity is controlled to create a well-exposed image.",
        "parent_slug": None,
        "difficulty": 2,
        "sort_order": 0,
    },
    {
        "slug": "composition",
        "title": "Composition",
        "description": "Arranging visual elements to guide the viewer's eye.",
        "parent_slug": None,
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "lighting",
        "title": "Lighting",
        "description": "Understanding and shaping natural and artificial light.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 2,
    },
    {
        "slug": "lens-and-focus",
        "title": "Lens & Focus",
        "description": "Focal length, depth of field, and focus techniques.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 3,
    },
    {
        "slug": "post-processing",
        "title": "Post-Processing",
        "description": "Editing techniques to enhance and stylise images.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 4,
    },
    # ── Exposure topics ────────────────────────────────────────────────────────
    {
        "slug": "aperture",
        "title": "Aperture",
        "description": "The opening in the lens that controls light and depth of field.",
        "parent_slug": "exposure",
        "difficulty": 2,
        "sort_order": 0,
    },
    {
        "slug": "shutter-speed",
        "title": "Shutter Speed",
        "description": "How long the sensor is exposed to light; freezes or blurs motion.",
        "parent_slug": "exposure",
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "iso",
        "title": "ISO",
        "description": "Sensor sensitivity to light; higher ISO introduces grain/noise.",
        "parent_slug": "exposure",
        "difficulty": 1,
        "sort_order": 2,
    },
    {
        "slug": "exposure-triangle",
        "title": "Exposure Triangle",
        "description": "The relationship between aperture, shutter speed, and ISO.",
        "parent_slug": "exposure",
        "difficulty": 3,
        "sort_order": 3,
    },
    {
        "slug": "histogram",
        "title": "Histogram",
        "description": "Reading a histogram to evaluate tonal distribution.",
        "parent_slug": "exposure",
        "difficulty": 3,
        "sort_order": 4,
    },
    # ── Composition topics ─────────────────────────────────────────────────────
    {
        "slug": "rule-of-thirds",
        "title": "Rule of Thirds",
        "description": "Dividing the frame into thirds to place subjects off-centre.",
        "parent_slug": "composition",
        "difficulty": 1,
        "sort_order": 0,
    },
    {
        "slug": "leading-lines",
        "title": "Leading Lines",
        "description": "Using lines in the scene to draw the eye toward the subject.",
        "parent_slug": "composition",
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "framing",
        "title": "Framing",
        "description": "Using foreground elements to frame the main subject.",
        "parent_slug": "composition",
        "difficulty": 2,
        "sort_order": 2,
    },
    {
        "slug": "negative-space",
        "title": "Negative Space",
        "description": "Intentional empty area around a subject to create emphasis.",
        "parent_slug": "composition",
        "difficulty": 3,
        "sort_order": 3,
    },
    {
        "slug": "golden-ratio",
        "title": "Golden Ratio",
        "description": "A classical proportion used to create harmonious compositions.",
        "parent_slug": "composition",
        "difficulty": 4,
        "sort_order": 4,
    },
    # ── Lighting topics ────────────────────────────────────────────────────────
    {
        "slug": "golden-hour",
        "title": "Golden Hour",
        "description": "Warm, soft light shortly after sunrise and before sunset.",
        "parent_slug": "lighting",
        "difficulty": 2,
        "sort_order": 0,
    },
    {
        "slug": "blue-hour",
        "title": "Blue Hour",
        "description": "Cool ambient light in the twilight period before sunrise or after sunset.",
        "parent_slug": "lighting",
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "catchlight",
        "title": "Catchlight",
        "description": "Specular highlight in the subject's eye that adds life to portraits.",
        "parent_slug": "lighting",
        "difficulty": 3,
        "sort_order": 2,
    },
    {
        "slug": "fill-flash",
        "title": "Fill Flash",
        "description": "Using flash to soften shadows in bright ambient conditions.",
        "parent_slug": "lighting",
        "difficulty": 3,
        "sort_order": 3,
    },
    {
        "slug": "rembrandt-lighting",
        "title": "Rembrandt Lighting",
        "description": "A portrait lighting pattern creating a small triangle of light on the cheek.",
        "parent_slug": "lighting",
        "difficulty": 4,
        "sort_order": 4,
    },
    # ── Lens & Focus topics ────────────────────────────────────────────────────
    {
        "slug": "depth-of-field",
        "title": "Depth of Field",
        "description": "The range of distance in a scene that appears acceptably sharp.",
        "parent_slug": "lens-and-focus",
        "difficulty": 3,
        "sort_order": 0,
    },
    {
        "slug": "focal-length",
        "title": "Focal Length",
        "description": "How focal length affects angle of view and subject compression.",
        "parent_slug": "lens-and-focus",
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "bokeh",
        "title": "Bokeh",
        "description": "The aesthetic quality of the out-of-focus blur in an image.",
        "parent_slug": "lens-and-focus",
        "difficulty": 3,
        "sort_order": 2,
    },
    {
        "slug": "hyperfocal-distance",
        "title": "Hyperfocal Distance",
        "description": "The focus distance that maximises depth of field for a given aperture.",
        "parent_slug": "lens-and-focus",
        "difficulty": 4,
        "sort_order": 3,
    },
    # ── Post-Processing topics ─────────────────────────────────────────────────
    {
        "slug": "white-balance",
        "title": "White Balance",
        "description": "Correcting colour cast caused by different light sources.",
        "parent_slug": "post-processing",
        "difficulty": 2,
        "sort_order": 0,
    },
    {
        "slug": "exposure-correction",
        "title": "Exposure Correction",
        "description": "Adjusting overall brightness and recovering highlights or shadows.",
        "parent_slug": "post-processing",
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "color-grading",
        "title": "Color Grading",
        "description": "Stylistic colour adjustment to create a particular mood or look.",
        "parent_slug": "post-processing",
        "difficulty": 4,
        "sort_order": 2,
    },
]
