TOPICS: list[dict] = [
    # ── Root categories (DB hierarchy only — no level/curriculum fields) ────────
    {
        "slug": "exposure",
        "title": "Exposure",
        "description": "How light quantity is controlled to create a well-exposed image.",
        "parent_slug": None,
        "difficulty": 2,
        "sort_order": 0,
    },
    {
        "slug": "composition",
        "title": "Composition",
        "description": "Arranging visual elements to guide the viewer's eye.",
        "parent_slug": None,
        "difficulty": 2,
        "sort_order": 1,
    },
    {
        "slug": "lighting",
        "title": "Lighting",
        "description": "Understanding and shaping natural and artificial light.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 2,
    },
    {
        "slug": "lens-and-focus",
        "title": "Lens & Focus",
        "description": "Focal length, depth of field, and focus techniques.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 3,
    },
    {
        "slug": "post-processing",
        "title": "Post-Processing",
        "description": "Editing techniques to enhance and stylise images.",
        "parent_slug": None,
        "difficulty": 3,
        "sort_order": 4,
    },

    # ── BEGINNER topics (sort_order = curriculum order within beginner level) ───

    {
        "slug": "iso",
        "title": "ISO",
        "description": "Sensor sensitivity to light; higher ISO introduces grain/noise.",
        "parent_slug": "exposure",
        "difficulty": 1,
        "sort_order": 2,  # DB sort within exposure parent
        "level": "beginner",
        "curriculum_order": 0,
        "teaching_points": [
            "ISO measures how sensitive your camera sensor is to light — lower numbers (100–400) mean less sensitivity and cleaner images; higher numbers (800–6400+) let you shoot in dim light but add grain.",
            "The practical rule: use the lowest ISO that still gives you a correct exposure to maximise image quality.",
            "On smartphones ISO is often controlled automatically, but understanding it helps when switching to manual or Pro mode.",
            "Grain (or 'noise') from high ISO is not always bad — it can add a film-like aesthetic when used intentionally.",
        ],
        "assessment_questions": [
            "If you're shooting in a dark room without flash, which direction would you move your ISO — higher or lower? Why?",
            "What trade-off do you accept when you raise ISO to ISO 3200?",
        ],
    },
    {
        "slug": "shutter-speed",
        "title": "Shutter Speed",
        "description": "How long the sensor is exposed to light; freezes or blurs motion.",
        "parent_slug": "exposure",
        "difficulty": 2,
        "sort_order": 1,
        "level": "beginner",
        "curriculum_order": 1,
        "teaching_points": [
            "Shutter speed is the duration the camera sensor is exposed to light, written as a fraction (1/500s) or whole seconds (2s).",
            "Fast shutter speeds (1/500s and above) freeze motion — great for sports, birds in flight, or splashing water.",
            "Slow shutter speeds (1/30s and below) blur motion — used creatively for silky waterfalls, light trails, or panning shots.",
            "A practical rule of thumb: to avoid camera-shake blur when hand-holding, use a shutter speed at least as fast as 1/(focal length in mm).",
        ],
        "assessment_questions": [
            "You're photographing a footballer running. Would you choose 1/60s or 1/1000s? Explain your thinking.",
            "What effect would a 1-second shutter speed have on a flowing river?",
        ],
    },
    {
        "slug": "aperture",
        "title": "Aperture",
        "description": "The opening in the lens that controls light and depth of field.",
        "parent_slug": "exposure",
        "difficulty": 2,
        "sort_order": 0,
        "level": "beginner",
        "curriculum_order": 2,
        "teaching_points": [
            "Aperture is the size of the opening in your lens, measured in f-stops — lower f-numbers (f/1.8) mean a wider opening; higher (f/16) mean a narrower one.",
            "A wide aperture (low f-number) lets in more light and blurs the background — ideal for portraits.",
            "A narrow aperture (high f-number) lets in less light and keeps more of the scene in focus — ideal for landscapes.",
            "Aperture is one of the three pillars of exposure, alongside shutter speed and ISO.",
        ],
        "assessment_questions": [
            "You want a sharp photo of a mountain range from foreground to background. Would you choose f/2 or f/11?",
            "What does a low f-number like f/1.8 do to your background?",
        ],
    },
    {
        "slug": "exposure-triangle",
        "title": "Exposure Triangle",
        "description": "The relationship between aperture, shutter speed, and ISO.",
        "parent_slug": "exposure",
        "difficulty": 3,
        "sort_order": 3,
        "level": "beginner",
        "curriculum_order": 3,
        "teaching_points": [
            "The exposure triangle describes how aperture, shutter speed, and ISO work together to determine the brightness of a photo.",
            "Changing one element affects the others: opening the aperture lets in more light, so you may need a faster shutter speed or lower ISO to compensate.",
            "A correct exposure means the image is neither too bright (overexposed) nor too dark (underexposed).",
            "Mastering the triangle is the gateway to full manual control — once you understand it, you can achieve any creative effect.",
        ],
        "assessment_questions": [
            "You open your aperture from f/8 to f/4. To keep the same exposure, what would you do to shutter speed?",
            "Why can't you just always use f/1.8, ISO 100, and 1/1000s for every shot?",
        ],
    },
    {
        "slug": "rule-of-thirds",
        "title": "Rule of Thirds",
        "description": "Dividing the frame into thirds to place subjects off-centre.",
        "parent_slug": "composition",
        "difficulty": 1,
        "sort_order": 0,
        "level": "beginner",
        "curriculum_order": 4,
        "teaching_points": [
            "Imagine your frame divided by two horizontal and two vertical lines into nine equal sections — the four intersection points are power points where the eye naturally travels.",
            "Placing your subject on one of these points (rather than dead-centre) creates a more dynamic, balanced composition.",
            "Most cameras and phones have a grid overlay you can enable to practise this instantly.",
            "The rule of thirds is a guideline, not a law — knowing when to break it intentionally is part of developing your visual style.",
        ],
        "assessment_questions": [
            "You're photographing a person against a landscape. Where on the frame would you place their eyes using the rule of thirds?",
            "Can you think of a type of photo where placing the subject dead-centre actually works better?",
        ],
    },
    {
        "slug": "leading-lines",
        "title": "Leading Lines",
        "description": "Using lines in the scene to draw the eye toward the subject.",
        "parent_slug": "composition",
        "difficulty": 2,
        "sort_order": 1,
        "level": "beginner",
        "curriculum_order": 5,
        "teaching_points": [
            "Leading lines are natural or man-made lines in a scene — roads, fences, rivers, staircases — that guide the viewer's eye toward the main subject.",
            "Diagonal lines create energy and movement; curved lines feel graceful and natural; converging lines create a strong sense of depth.",
            "Look for leading lines when composing: position yourself so a line starts near the edge of the frame and points toward your subject.",
            "Leading lines work even when subtle — a shadow, a row of trees, or the line of a horizon can all serve this purpose.",
        ],
        "assessment_questions": [
            "You're on a straight road stretching to the horizon. How would you use the road as a leading line in your composition?",
            "What's the difference in mood between a straight leading line and a curved one?",
        ],
    },
    {
        "slug": "focal-length",
        "title": "Focal Length",
        "description": "How focal length affects angle of view and subject compression.",
        "parent_slug": "lens-and-focus",
        "difficulty": 2,
        "sort_order": 1,
        "level": "beginner",
        "curriculum_order": 6,
        "teaching_points": [
            "Focal length (measured in mm) determines how much of a scene your lens captures: wide (14–35mm) shows a broad view; standard (35–85mm) resembles human vision; telephoto (85mm+) narrows the view and magnifies distant subjects.",
            "Wider focal lengths exaggerate perspective and make distances between objects seem greater; telephoto lengths compress perspective and flatten distances.",
            "For portraits, 50–85mm is flattering because it avoids the distortion a very wide lens introduces to facial features.",
            "On a smartphone, switching between camera lenses (0.5×, 1×, 2×) is effectively changing focal length.",
        ],
        "assessment_questions": [
            "A wildlife photographer wants to photograph a bird 50 metres away without disturbing it. Should they use a 24mm or a 400mm lens?",
            "Why is a 35mm lens generally considered more flattering for portraits than an 18mm lens?",
        ],
    },
    {
        "slug": "golden-hour",
        "title": "Golden Hour",
        "description": "Warm, soft light shortly after sunrise and before sunset.",
        "parent_slug": "lighting",
        "difficulty": 2,
        "sort_order": 0,
        "level": "beginner",
        "curriculum_order": 7,
        "teaching_points": [
            "Golden hour is the roughly 30–60 minutes after sunrise and before sunset when sunlight is warm, low-angled, and soft — the most forgiving and flattering light for almost any subject.",
            "The low angle of the sun creates long shadows and dimensional texture that flat midday light eliminates.",
            "Skin tones look naturally warm and healthy; landscapes glow with orange and gold.",
            "Planning tip: use a free app like PhotoPills or The Photographer's Ephemeris to know exactly when golden hour starts at your location.",
        ],
        "assessment_questions": [
            "Why does golden hour light look so different from midday light, even though it comes from the same sun?",
            "You have one hour to photograph an outdoor portrait. Would you choose noon or 7pm on a summer evening? Why?",
        ],
    },

    # ── INTERMEDIATE topics ──────────────────────────────────────────────────────

    {
        "slug": "depth-of-field",
        "title": "Depth of Field",
        "description": "The range of distance in a scene that appears acceptably sharp.",
        "parent_slug": "lens-and-focus",
        "difficulty": 3,
        "sort_order": 0,
        "level": "intermediate",
        "curriculum_order": 0,
        "teaching_points": [
            "Depth of field (DoF) is how much of the scene, front to back, is in sharp focus. Shallow DoF = only a thin slice in focus; deep DoF = most of the scene sharp.",
            "Three factors control DoF: aperture (wider = shallower), focal length (longer = shallower), and distance to subject (closer = shallower).",
            "Shallow DoF is commonly used to isolate subjects (portraits, product shots). Deep DoF is used for landscapes and architecture where front-to-back sharpness matters.",
            "Understanding DoF lets you make deliberate choices rather than accidentally blurring backgrounds or keeping distracting elements in focus.",
        ],
        "assessment_questions": [
            "You're shooting a flower close-up at f/2.8 with a 100mm macro lens. What do you expect the depth of field to look like?",
            "What three things could you change to make the background of a portrait more blurred?",
        ],
    },
    {
        "slug": "histogram",
        "title": "Histogram",
        "description": "Reading a histogram to evaluate tonal distribution.",
        "parent_slug": "exposure",
        "difficulty": 3,
        "sort_order": 4,
        "level": "intermediate",
        "curriculum_order": 1,
        "teaching_points": [
            "A histogram is a graph showing the distribution of tones in your image from pure black (left) to pure white (right). The height of the bars shows how many pixels are at each brightness.",
            "Peaks pushed hard against the right edge indicate blown highlights (lost detail); peaks against the left edge indicate crushed shadows. Either can be a problem depending on the scene.",
            "There is no universally 'correct' histogram shape — a high-key portrait and a night street scene will look very different, and both can be correct.",
            "Practise checking the histogram in-camera to evaluate exposure without relying solely on the LCD screen, which can be misleading in bright sunlight.",
        ],
        "assessment_questions": [
            "What does it mean when the histogram shows a spike clipped against the right edge?",
            "You're shooting a snow scene and your histogram is centred in the middle. Is that likely a good exposure? Why or why not?",
        ],
    },
    {
        "slug": "framing",
        "title": "Framing",
        "description": "Using foreground elements to frame the main subject.",
        "parent_slug": "composition",
        "difficulty": 2,
        "sort_order": 2,
        "level": "intermediate",
        "curriculum_order": 2,
        "teaching_points": [
            "Framing means using elements in the scene — doorways, windows, arches, trees, overhanging branches — to create a visual frame around your subject.",
            "A frame within a frame draws the viewer's eye to the subject and adds depth and context to the image.",
            "The framing element doesn't need to be sharp — a blurred foreground frame can work beautifully to create layers.",
            "Look for natural frames when scouting: archways in architecture, gaps in foliage, reflections in glass.",
        ],
        "assessment_questions": [
            "You're photographing a statue in a park. What natural elements nearby could you use to frame it?",
            "How does adding a frame within the frame affect the viewer's experience of depth in the image?",
        ],
    },
    {
        "slug": "negative-space",
        "title": "Negative Space",
        "description": "Intentional empty area around a subject to create emphasis.",
        "parent_slug": "composition",
        "difficulty": 3,
        "sort_order": 3,
        "level": "intermediate",
        "curriculum_order": 3,
        "teaching_points": [
            "Negative space is the empty or unoccupied area around and between your subjects — sky, plain wall, calm water, open fields.",
            "Deliberate negative space makes the subject stand out more powerfully and gives the image a sense of breathing room and calm.",
            "It can also create a mood: vast negative space evokes loneliness, isolation, or freedom depending on context.",
            "Resist the beginner instinct to fill the frame — sometimes the most impactful choice is to leave space.",
        ],
        "assessment_questions": [
            "A single bird perched on a wire against a clear sky — how does the sky's negative space contribute to the image?",
            "When might too much negative space become a weakness rather than a strength?",
        ],
    },
    {
        "slug": "blue-hour",
        "title": "Blue Hour",
        "description": "Cool ambient light in the twilight period before sunrise or after sunset.",
        "parent_slug": "lighting",
        "difficulty": 2,
        "sort_order": 1,
        "level": "intermediate",
        "curriculum_order": 4,
        "teaching_points": [
            "Blue hour occurs roughly 20–30 minutes before sunrise or after sunset, when the sun is below the horizon and the sky glows a deep, cool blue.",
            "During blue hour, artificial lights (streetlamps, shop windows, car headlights) are lit and balanced against the ambient sky — this balance creates striking cityscapes.",
            "Light levels drop quickly, so longer exposures (tripod essential) and higher ISOs become necessary.",
            "Blue hour light is often more dramatic and controllable than golden hour for urban architecture photography.",
        ],
        "assessment_questions": [
            "Why do cityscape photographers often prefer blue hour over golden hour for their shots?",
            "What equipment would you need to shoot handheld during blue hour, and what settings would you adjust?",
        ],
    },
    {
        "slug": "fill-flash",
        "title": "Fill Flash",
        "description": "Using flash to soften shadows in bright ambient conditions.",
        "parent_slug": "lighting",
        "difficulty": 3,
        "sort_order": 3,
        "level": "intermediate",
        "curriculum_order": 5,
        "teaching_points": [
            "Fill flash is using a flash (or pop-up flash) to add a small amount of light that fills in dark shadows, typically in bright sunlit conditions.",
            "It's most commonly used for outdoor portraits on bright days where the sun creates harsh under-eye shadows or when the subject is backlit.",
            "The key is subtlety — you want the flash to appear as natural fill light, not as an obvious flash. Reduce flash power to -1 or -2 EV from the metered exposure.",
            "On smartphones, look for 'fill flash' or forced flash mode, or position your subject with a reflector for a natural-light version.",
        ],
        "assessment_questions": [
            "You're photographing someone with the sun behind them. Their face is in shadow. What would fill flash do in this situation?",
            "Why is it important to reduce flash power when using fill flash rather than using it at full power?",
        ],
    },
    {
        "slug": "catchlight",
        "title": "Catchlight",
        "description": "Specular highlight in the subject's eye that adds life to portraits.",
        "parent_slug": "lighting",
        "difficulty": 3,
        "sort_order": 2,
        "level": "intermediate",
        "curriculum_order": 6,
        "teaching_points": [
            "A catchlight is a small, bright reflection of a light source visible in a subject's eye — it makes eyes look alive, engaged, and three-dimensional.",
            "Position your light source (window, reflector, or flash) so it reflects in the upper half of the eye for the most natural look.",
            "The shape of the catchlight reveals the light source: circular = softbox or reflector; rectangular = window light; tiny point = direct flash.",
            "Without a catchlight, eyes can look flat, dead, or disengaged — check for it in your viewfinder before shooting portraits.",
        ],
        "assessment_questions": [
            "You're shooting a portrait and notice the subject's eyes look dull and flat. What might be causing this, and how would you fix it?",
            "What does the shape and position of a catchlight tell you about how the photo was lit?",
        ],
    },
    {
        "slug": "white-balance",
        "title": "White Balance",
        "description": "Correcting colour cast caused by different light sources.",
        "parent_slug": "post-processing",
        "difficulty": 2,
        "sort_order": 0,
        "level": "intermediate",
        "curriculum_order": 7,
        "teaching_points": [
            "White balance adjusts your camera (or editing software) to account for the colour temperature of your light source, ensuring whites look white and colours look natural.",
            "Different light sources have different colour temperatures: candlelight is very warm (~2000K); daylight is neutral (~5500K); overcast sky is cool (~7000K); fluorescent office light is greenish.",
            "Shooting in RAW format lets you change white balance non-destructively in post — in JPEG, an incorrect white balance is harder to fix.",
            "Intentional incorrect white balance can be a creative choice: warm white balance makes sunsets more golden; cool white balance can make a scene feel colder and more cinematic.",
        ],
        "assessment_questions": [
            "Your indoor photo under tungsten bulbs has an orange cast. What would you adjust to neutralise it?",
            "Why do photographers often prefer to shoot RAW rather than JPEG when they're unsure about white balance?",
        ],
    },
    {
        "slug": "exposure-correction",
        "title": "Exposure Correction",
        "description": "Adjusting overall brightness and recovering highlights or shadows.",
        "parent_slug": "post-processing",
        "difficulty": 2,
        "sort_order": 1,
        "level": "intermediate",
        "curriculum_order": 8,
        "teaching_points": [
            "Exposure correction in post-processing lets you brighten or darken the overall image, and separately recover detail in shadows and highlights.",
            "RAW files retain much more recoverable data in shadows and highlights than JPEGs — typically ±2–3 stops of recovery is possible.",
            "Highlights and shadows sliders work independently: you can pull back blown highlights while simultaneously lifting crushed shadows to reveal hidden detail.",
            "The goal is not to 'fix' a badly exposed image but to maximise the detail and dynamic range captured in the RAW file.",
        ],
        "assessment_questions": [
            "You've slightly underexposed a RAW portrait. What slider(s) in Lightroom or your editing app would you reach for first?",
            "What is the practical limit to how much you can recover from a completely blown-out highlight in a JPEG vs. a RAW file?",
        ],
    },

    # ── ADVANCED topics ──────────────────────────────────────────────────────────

    {
        "slug": "golden-ratio",
        "title": "Golden Ratio",
        "description": "A classical proportion used to create harmonious compositions.",
        "parent_slug": "composition",
        "difficulty": 4,
        "sort_order": 4,
        "level": "advanced",
        "curriculum_order": 0,
        "teaching_points": [
            "The golden ratio (approximately 1:1.618) is a mathematical proportion found in nature and classical art that the human eye perceives as inherently balanced and beautiful.",
            "The golden spiral (a logarithmic spiral based on the ratio) can be used as a compositional guide: place the subject at the spiral's tight end and let the scene flow outward.",
            "Unlike the rule of thirds, the golden ratio places the focal point slightly different — understanding both lets you choose the right tool for each image.",
            "It appears naturally in flower spirals, nautilus shells, and wave curves — training yourself to see it in real scenes improves compositional instinct.",
        ],
        "assessment_questions": [
            "How does the golden ratio's focal point differ from a rule-of-thirds intersection point, and when might you prefer one over the other?",
            "You've framed a coastal landscape with a winding cliff path. How could you use the golden spiral to guide that composition?",
        ],
    },
    {
        "slug": "bokeh",
        "title": "Bokeh",
        "description": "The aesthetic quality of the out-of-focus blur in an image.",
        "parent_slug": "lens-and-focus",
        "difficulty": 3,
        "sort_order": 2,
        "level": "advanced",
        "curriculum_order": 1,
        "teaching_points": [
            "Bokeh refers to the aesthetic quality of out-of-focus areas in an image, particularly the shape and smoothness of blurred background highlights.",
            "Smooth, circular bokeh is generally considered pleasing and is produced by lenses with circular aperture blades and wide maximum apertures.",
            "Bokeh shape is determined by the aperture blade count and shape: fewer straight blades create geometric bokeh; rounded blades create circular bokeh.",
            "Subject-to-background distance matters as much as aperture: a background far behind your subject produces creamier bokeh than one close behind it.",
        ],
        "assessment_questions": [
            "A photographer says a lens has 'beautiful bokeh.' What specifically about the out-of-focus rendering are they likely describing?",
            "You're shooting at f/1.8. What else could you do to make the background even more blurred and aesthetically pleasing?",
        ],
    },
    {
        "slug": "rembrandt-lighting",
        "title": "Rembrandt Lighting",
        "description": "A portrait lighting pattern creating a small triangle of light on the cheek.",
        "parent_slug": "lighting",
        "difficulty": 4,
        "sort_order": 4,
        "level": "advanced",
        "curriculum_order": 2,
        "teaching_points": [
            "Rembrandt lighting is a classic portrait pattern where the main light is positioned high and to one side at roughly 45°, creating a small triangle of light on the shadow-side cheek.",
            "It is characterised by one side of the face being well-lit and the other in shadow, with only that small triangle breaking the shadow on the darker side.",
            "The technique creates a dramatic, dimensional, and painterly look — named for the Dutch master's characteristic use of the same lighting in oil portraits.",
            "Achieved with a single light source (window, softbox, reflector): position the light above and to one side, then have the subject turn slightly away from the light until the triangle appears.",
        ],
        "assessment_questions": [
            "Describe the position of the light source needed to achieve Rembrandt lighting on a portrait subject.",
            "How does Rembrandt lighting differ from a flat, frontal lighting setup in terms of mood and dimensionality?",
        ],
    },
    {
        "slug": "hyperfocal-distance",
        "title": "Hyperfocal Distance",
        "description": "The focus distance that maximises depth of field for a given aperture.",
        "parent_slug": "lens-and-focus",
        "difficulty": 4,
        "sort_order": 3,
        "level": "advanced",
        "curriculum_order": 3,
        "teaching_points": [
            "Hyperfocal distance is the closest focus distance at which objects at infinity are still acceptably sharp — focusing at it maximises your depth of field for a given lens and aperture combination.",
            "When focused at the hyperfocal distance, everything from half that distance to infinity will be in acceptable focus — ideal for landscape and street photography.",
            "Hyperfocal distance decreases as aperture narrows (higher f-number) and as focal length shortens — a 24mm lens at f/11 has a much shorter hyperfocal distance than a 50mm at f/4.",
            "Use a hyperfocal distance calculator app or chart to find exact values; once understood, zone focusing becomes an instinctive part of your shooting workflow.",
        ],
        "assessment_questions": [
            "Why does using hyperfocal distance matter more for a landscape photographer than for a portrait photographer?",
            "You're shooting a street scene with a 28mm lens at f/8. If the hyperfocal distance is 3.5m, what range of the scene will be in focus?",
        ],
    },
    {
        "slug": "color-grading",
        "title": "Color Grading",
        "description": "Stylistic colour adjustment to create a particular mood or look.",
        "parent_slug": "post-processing",
        "difficulty": 4,
        "sort_order": 2,
        "level": "advanced",
        "curriculum_order": 4,
        "teaching_points": [
            "Colour grading is the creative manipulation of colour beyond technical correction — it imposes a visual style or emotional tone on an image.",
            "Key tools: HSL (Hue, Saturation, Luminance) for per-colour control; split toning (or colour wheels) for adding distinct hues to shadows and highlights; tone curves for contrast and colour channel manipulation.",
            "Common looks: the 'cinematic' teal-and-orange look lifts shadow tones to teal while warming highlights; film emulation looks desaturate and add grain.",
            "Good colour grading serves the story or emotion of the image — it should feel intentional, not accidental.",
        ],
        "assessment_questions": [
            "What's the difference between colour correction and colour grading?",
            "If you wanted to give a portrait a warm, moody, golden-toned look, which tools and adjustments would you start with?",
        ],
    },
    {
        "slug": "long-exposure",
        "title": "Long Exposure",
        "description": "Using slow shutter speeds to capture motion blur and light trails over time.",
        "parent_slug": "exposure",
        "difficulty": 4,
        "sort_order": 5,
        "level": "advanced",
        "curriculum_order": 5,
        "teaching_points": [
            "Long exposure photography uses shutter speeds from half a second to many minutes, turning moving elements (water, clouds, traffic, stars) into smooth trails or silky textures.",
            "A sturdy tripod is essential — even slight camera movement during a long exposure produces an unrecoverably blurred image.",
            "Neutral density (ND) filters reduce the amount of light entering the lens, allowing long exposures even in bright daylight without overexposing.",
            "Light trails from car headlights require 5–20 seconds; star trails require 20+ minutes; silky waterfalls can be achieved in as little as 0.5–2 seconds.",
        ],
        "assessment_questions": [
            "You want to photograph a busy road at dusk to capture car light trails. Walk me through the settings and equipment you'd use.",
            "Why is an ND filter useful for long exposure photography in bright conditions?",
        ],
    },
    {
        "slug": "panning",
        "title": "Panning",
        "description": "Tracking a moving subject with a slow shutter to blur the background while keeping the subject sharp.",
        "parent_slug": "lens-and-focus",
        "difficulty": 4,
        "sort_order": 4,
        "level": "advanced",
        "curriculum_order": 6,
        "teaching_points": [
            "Panning is a technique where you follow (pan) a moving subject with your camera during a slow shutter exposure — the subject stays relatively sharp while the background blurs into horizontal streaks, conveying speed.",
            "Typical panning shutter speeds are 1/30s to 1/100s depending on subject speed — start slower for faster subjects and experiment from there.",
            "A smooth, consistent follow-through is critical: start tracking the subject before pressing the shutter and continue following after.",
            "Panning works best with subjects moving horizontally across the frame at a predictable pace: cyclists, runners, motorcycles, racehorses.",
        ],
        "assessment_questions": [
            "What shutter speed range would you start experimenting with when panning a cyclist at moderate speed, and why?",
            "What separates a successful panning shot from one where both subject and background are blurred?",
        ],
    },
    {
        "slug": "light-painting",
        "title": "Light Painting",
        "description": "Moving a light source during a long exposure to draw or illuminate in the frame.",
        "parent_slug": "exposure",
        "difficulty": 4,
        "sort_order": 6,
        "level": "advanced",
        "curriculum_order": 7,
        "teaching_points": [
            "Light painting uses a long exposure (typically 5–30 seconds) in a dark environment while you move a light source — torch, phone screen, sparkler — to draw shapes, illuminate subjects, or add creative highlights.",
            "Camera setup: tripod mandatory; set to Bulb mode or a long timed exposure; aperture f/8 to f/11 for sharpness; ISO 100–400 to keep noise low.",
            "The light source is only visible where it moves — a torch pointed at the camera writes 'in the air'; one pointed away illuminates surfaces selectively.",
            "Start with a simple word or shape in complete darkness to understand timing and movement before attempting complex scenes.",
        ],
        "assessment_questions": [
            "You want to light-paint the word 'PHOTO' in front of a dark building. Describe your camera settings and how you'd execute the shot.",
            "How does pointing a torch toward the camera differ from pointing it away from the camera in a light painting exposure?",
        ],
    },
]
